In [18]:
folder_1 = 'fly1_20sblahblah_func-001'
folder_2 = 'fly1_20smorestuff_anat-003'
test_1 = 'something_else'

def get_fly_number (file):
    """looks for "fly" in file and returns number following"""
    if 'fly' not in file or '_' not in file:
        print(f'ERROR: No appropriate flyid found in "{file}"')
        return None
    else:
        number_start = file.find('fly') + 3
        first_hyphen = file.find('_')
        number = file[number_start:first_hyphen]
        return number
   

A = get_fly_number(folder_1)
print('a', A)
B = get_fly_number(test_1)


print('b', B)

a 1
ERROR: No appropriate flyid found in "something_else"
b None


In [21]:
path = '/home/users/asmart/projects/new_brainsss/scripts'
print(os.path.split(path))
print(os.path.dirname(path))

('/home/users/asmart/projects/new_brainsss', 'scripts')
/home/users/asmart/projects/new_brainsss


In [19]:
import sys
import os
#print(os.path.split(os.path.dirname(__file__))[0])

NameError: name '__file__' is not defined

In [1]:
import numpy as np

c:\Users\ashsm\Anaconda3\envs\cme193\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\ashsm\Anaconda3\envs\cme193\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
c:\Users\ashsm\Anaconda3\envs\cme193\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


In [27]:
a = [[[[1,1],[2,2],[3,3], [4,4]], [[1,1],[2,2],[3,3], [4,4]]], [[[1,1],[2,2],[3,3], [4,4]], [[1,1],[2,2],[3,3], [4,4]]]]
a = np.array(a)
print(np.shape(a))
print(a)
shape = np.shape(a)

blank = np.empty((shape[0], shape[1], shape[2],1)) * np.nan
print(blank)
print(np.shape(blank))

new_a = np.append(a,blank, axis =3)
print(new_a)
print(np.shape(new_a))
#print(np.insert(a, -1, blank), axis = 3)

stitch_a = np.concatenate(new_a, axis = -1)
print(stitch_a)
print(np.shape(stitch_a))


(2, 2, 4, 2)
[[[[1 1]
   [2 2]
   [3 3]
   [4 4]]

  [[1 1]
   [2 2]
   [3 3]
   [4 4]]]


 [[[1 1]
   [2 2]
   [3 3]
   [4 4]]

  [[1 1]
   [2 2]
   [3 3]
   [4 4]]]]
[[[[nan]
   [nan]
   [nan]
   [nan]]

  [[nan]
   [nan]
   [nan]
   [nan]]]


 [[[nan]
   [nan]
   [nan]
   [nan]]

  [[nan]
   [nan]
   [nan]
   [nan]]]]
(2, 2, 4, 1)
[[[[ 1.  1. nan]
   [ 2.  2. nan]
   [ 3.  3. nan]
   [ 4.  4. nan]]

  [[ 1.  1. nan]
   [ 2.  2. nan]
   [ 3.  3. nan]
   [ 4.  4. nan]]]


 [[[ 1.  1. nan]
   [ 2.  2. nan]
   [ 3.  3. nan]
   [ 4.  4. nan]]

  [[ 1.  1. nan]
   [ 2.  2. nan]
   [ 3.  3. nan]
   [ 4.  4. nan]]]]
(2, 2, 4, 3)
[[[ 1.  1. nan  1.  1. nan]
  [ 2.  2. nan  2.  2. nan]
  [ 3.  3. nan  3.  3. nan]
  [ 4.  4. nan  4.  4. nan]]

 [[ 1.  1. nan  1.  1. nan]
  [ 2.  2. nan  2.  2. nan]
  [ 3.  3. nan  3.  3. nan]
  [ 4.  4. nan  4.  4. nan]]]
(2, 4, 6)
